# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "username" varchar not null,
  "password" varchar not null,
  "is_deleted" bit not null
);

insert into "users" ("username", "password", "is_deleted") values ('xittz', '1234', 0);
insert into "users" ("username", "password", "is_deleted") values ('admin', 'weqweq', 0);
insert into "users" ("username", "password", "is_deleted") values ('iwbbtt', 'weq4234234', 0);

# --- !Downs

drop table "users" if exists;
