# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "username" varchar not null,
  "password" varchar not null,
  "isDeleted" bit not null
);

insert into "users" ("username", "password", "isDeleted") values ('xittz', '1234', 0);
insert into "users" ("username", "password", "isDeleted") values ('admin', 'weqweq', 0);

# --- !Downs

drop table "users" if exists;
